# Generated by Django 4.0.2 on 2022-12-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('mfg_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('ingredients', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
    ]
